// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVslo3L9xov35TK_FzrDu3-l092F9u8ww',
    appId: '1:210400931416:android:c74cbf033c361d054f642d',
    messagingSenderId: '210400931416',
    projectId: 'notification-app-123456',
    storageBucket: 'notification-app-123456.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEWrJDKhm3uGs8X43THPYJgT0_knmpFUw',
    appId: '1:210400931416:ios:4028c186273ecf294f642d',
    messagingSenderId: '210400931416',
    projectId: 'notification-app-123456',
    storageBucket: 'notification-app-123456.firebasestorage.app',
    iosBundleId: 'com.example.notifyapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFKAeQu3ZYTtyOQ0ZwrcUNxMTA8tRP5Uw',
    appId: '1:210400931416:web:6c936727c2ef9f694f642d',
    messagingSenderId: '210400931416',
    projectId: 'notification-app-123456',
    authDomain: 'notification-app-123456.firebaseapp.com',
    storageBucket: 'notification-app-123456.firebasestorage.app',
  );
}
